import './globals.css'
import { Inter } from 'next/font/google'
import "cal-sans";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jakub Stranianek | Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " selection:bg-[#13EF9A] selection:text-black"}>{children}</body>
    </html>
  )
}
