import './globals.css'
import { Inter } from 'next/font/google'
import {useLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import "cal-sans";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jakub Stranianek | Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }) {
  const locale = useLocale();

  // Validate that the incoming `locale` parameter is a valid locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={inter.className + " selection:bg-[#13EF9A] selection:text-black"}>{children}</body>
    </html>
  )
}
